#!/bin/bash
# This is a simple build script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.
#
#

cd ${OPENSHIFT_REPO_DIR}

ln -s "$OPENSHIFT_DATA_DIR/node_modules" ./node_modules
ln -s "$OPENSHIFT_DATA_DIR/bower_components" ./bower_components
${OPENSHIFT_DATA_DIR}/node/bin/node ./node_modules/grunt-cli/bin/grunt build
